players: 5

image:
  repository: ghcr.io/mathisdlmr/sr05-projet
  tag: sha-323598f
  pullPolicy: IfNotPresent

namespace: werewolf

shared:
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  storage: 64Mi

nodeSelector: {}

ports:
  http: 4444

web:
  # joueur i accessible sur j{i}-{domainSuffix}
  # Ex : werewolf.mdlmr.fr -> "j1-werewolf.mdlmr.fr"
  domainSuffix: werewolf.mdlmr.fr
